name: Coveralls

on:
  push:
    branches: [master]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov g++

    - name: Generate coverage
      run: |
        chmod +x .github/coverage.sh
        ./.github/coverage.sh
        
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        path-to-lcov: build_coverage/coverage.filtered.info
        flag-name: linux-ubuntu
