name: Docker Build and Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run-docker.sh
      run: ./run_docker.sh
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          test_results.log
          cppcheck.log
          build/
        retention-days: 7
