name: Build

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./banking

    steps:
      - uses: actions/checkout@v4
          
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev libgmock-dev



          
      - name: Configure and build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Coverage -DENABLE_COVERAGE=ON ..
          make -j2
          
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
          
      - name: Generate coverage
        if: success()
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage
          
      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-report
          path: build/coverage

