name: Build, Test and Coverage

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          
      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ../banking
          make
          ctest --output-on-failure

  coverage:
    runs-on: ubuntu-22.04
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lcov
          
      - name: Build with coverage
        run: |
          mkdir coverage-build
          cd coverage-build
          cmake -DENABLE_COVERAGE=ON ../banking
          make
          
      - name: Generate coverage
        run: |
          cd coverage-build
          ctest --output-on-failure
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-build/coverage
