name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Install gtest and gmock
        run: |
          sudo apt-get install -y libgtest-dev libgmock-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib
          
      - name: Configure and build
        run: |
          mkdir build && cd build
          cmake ..
          make -j2
          
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

  coverage:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lcov

      - name: Configure and build with coverage
        run: |
          mkdir build && cd build
          cmake -DENABLE_COVERAGE=ON ..
          make -j2
          
      - name: Run tests for coverage
        run: |
          cd build
          ctest --output-on-failure
          
      - name: Generate coverage report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage
          
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage
